### ISSUE TITLE
Unable to add private repo to External Plugins Manager

### ISSUE THREAD

**Issue by nick-watson-hash** [jbx5/devious-client#52]
**Describe the bug**
On EXPERIMENTAL
When trying to add a private repo it populates this error message

When trying to add github repo - 
"Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 4 path $"

When trying to add raw repo -
"Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 7 column 1 path $"

**To Reproduce**
1. Run client in debug mode - no error populates outside of debug but no changed behavior witnessed
2. Go to 'External plugin manager'
3. Click on 'Add new raw or GitHub repository'
4. Fill out requested information
5. See error

**Expected behavior**
To be able to add repo.

**Additional context**
I believe the issue to be in "ExternalPluginManagerPanel" "OPRSExternalPluginManager" "PrivateUpdateRepository"

**Comment by melxin** [comment]
Tested and private repositories work fine, issue can be closed

**Comment by jbx5** [comment]
Thanks all.
