### ISSUE TITLE
Object And Npc Tagging Not Working

### ISSUE THREAD

**Issue by Blunkie** [jbx5/devious-client#79]
Object And NPC Tagging Not Showing Up When Marking An Object Or NPC.

**To Reproduce**
Mark An Object Or NPC.

**Expected behavior**
Not To Work
**Screenshots**
[[If applicable, add screenshots to help explain your problem.](https://i.gyazo.com/c2fcdb5ec56232ae62f47a358a0c5ceb.gif)

**Environment (please complete the following information):**
Windows
 - Devious Client Version: 1.0.16 Experimental
 - Launcher version: 1.0.1
 - Rev 211

**Comment by melxin** [comment]
Should have been resolved now by pull request: [](https://github.com/jbx5/devious-client/pull/78)
